workflow:
  rules:
    - when: always

default:
  image: rust:1.75-bullseye
  before_script:
    - apt-get update
    - apt-get install -y postgresql-client libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
    - apt-get install -y gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad
    - apt-get install -y gstreamer1.0-plugins-ugly gstreamer1.0-libav libgstrtspserver-1.0-dev libges-1.0-dev
    - rustc --version
    - cargo --version
    - echo 'DATABASE_URL="postgres://${PG_USER}:${PG_PASS}@${PG_HOST}/${PG_DB}"' >> .env
    - echo 'COOKIE_SESSION_KEY=${COOKIE_CI_SESSION_KEY}' >> .env

  tags:
    - shared-fi

stages:
  - build
  - preflight
  - tests

build:
  stage: build
  script:
    - cargo build --verbose

# dependencies_unchanged:
#   stage: preflight

# tests_unchanged:
#   stage: preflight

lint:
  stage: preflight
  script:
    - rustup component add rustfmt
#    - cargo fmt -- --check
    - rustup component add clippy
    - cargo check
#    - cargo clippy -- -D warnings

tests:
  stage: tests
  allow_failure: true
  script:
    - cargo test

