workflow:
  rules:
    - when: always

default:
  image: rust:alpine3.18
  before_script:
    - apk add --no-cache alpine-sdk
    - rustc --version
    - cargo --version
    - echo 'DATABASE_URL="postgres://${PG_USER}:${PG_PASS}@${PG_HOST}/${PG_DB}"' > .env

  tags:
    - shared-fi

stages:
  - build
  - preflight
  - tests

build:
  stage: build
  script:
    - cargo build --verbose

# dependencies_unchanged:
#   stage: preflight

# tests_unchanged:
#   stage: preflight

lint:
  stage: preflight
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo clippy -- -D warnings

tests:
  stage: tests
  allow_failure: true
  script:
    - cargo test

