[package]
name = "audiobooks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
chrono = "0.4.31"
dotenv = "0.15.0"
sqlx = { version = "0.7.2", features = ["chrono", "runtime-tokio-native-tls", "postgres"] }
tokio = { version = "1.34.0", features = ["full"] }
